name: SSE CI Workflow

on:
  push:
    branches:
      - "*"

jobs:
  style_check:
    name: style_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install black
        run: pip install black

      - name: Run black
        run: black --check .

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install pytest coverage numpy matplotlib

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
      - name: View coverage report
        run: |
          coverage report
      - name: Save coverage in xml
        run: |
          coverage xml          
      - name: Save coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: .coverage
          include-hidden-files: true
          retention-days: 1
      - name: Save coverage xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          retention-days: 14